- - 三年级
  - 北京版
  - 上册
- - 三年级
  - 北京版
  - 下册
- - 三年级
  - 北师大版
  - 下册
- - 三年级
  - 苏教版
  - 上册
- - 三年级
  - 苏教版
  - 下册
- - 三年级
  - 人教版
  - 上册
- - 三年级
  - 人教版
  - 下册
- - 四年级
  - 北京版
  - 上册
- - 四年级
  - 北京版
  - 下册
- - 四年级
  - 北师大版
  - 下册
- - 四年级
  - 苏教版
  - 上册
- - 四年级
  - 苏教版
  - 下册
- - 四年级
  - 人教版
  - 上册
- - 四年级
  - 人教版
  - 下册
